POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "esse é o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/03b34b4d-d6c3-4ffe-8993-988dd7b53399
Content-Type: application/json

{
    "title": "video 02",
    "description": "esse é o primeiro video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/03b34b4d-d6c3-4ffe-8993-988dd7b53399