POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "esse é o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/062c35d2-c7a0-48fe-b2b7-e7f355445773
Content-Type: application/json

{
    "title": "video 02",
    "description": "esse é o primeiro video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/062c35d2-c7a0-48fe-b2b7-e7f355445773